name: simple-obfs # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.0.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple-obfs is a plugin of shadowsocks. # 79 char long summary
description: |
  Simple-obfs is a simple obfuscating tool, designed as plugin server of shadowsocks.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  obfs-local:
    command: bin/obfs-local
    plugs: [network, network-bind]
  obfs-server:
    command: bin/obfs-server
    plugs: [network, network-bind]

parts:
  simple-obfs:
    # See 'snapcraft plugins'
    plugin: autotools
    source: https://github.com/ipcjs/simple-obfs.git
    build-packages:
      - git
      - build-essential
      - autoconf
      - libtool
      - libssl-dev
      - libpcre3-dev
      - libev-dev
      - asciidoc
      - xmlto
      - automake
    stage-packages:
      - libev4
      - libssl1.1
